version: "3.8"

services: 
    db:
        image: postgres:12.2-alpine
        container_name: "web-to-cli-database"
        ports:
            - "5432:5432"
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks: 
            - fullstack
        volumes:
            - database_postgres:/var/lib/postgresql/data
    
    api:
        build: .
        container_name: "web-2-cli-rest-api"
        environment: 
            DB_USERNAME: "postgres"
            DB_PASSWORD: "postgres"
            DB_DB: "postgres"
            DB_TABLE: "postgres"
            DB_HOST: "db"
            DB_PORT: "5432"
            SSL_MODE: "disable"
        ports: 
            - "8000:8000"
        depends_on: 
            - db
        networks: 
            - fullstack

volumes:
    database_postgres:

networks:
    fullstack:
        driver: bridge